---
# tasks file for ansible-role-mongodb_exporter

# mongodb_exporter configuration
- name: Create directory for mongodb_exporter
  ansible.builtin.file:
    path: /opt/mongodb_exporter/
    state: directory
    mode: '0755'

- name: Download and expand mongodb_exporter archive file
  ansible.builtin.unarchive:
    src: "{{ mongodb_exporter_tarball }}"
    dest: /opt/mongodb_exporter
    remote_src: true
    extra_opts:
      - --strip-components=1
  tags:
    - exporter
    - mongo

- name: Create service for mongodb_exporter
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/mongodb_exporter.service
    block: |
      [Unit]
      Description=Mongodb Exporter
      User=root

      [Service]
      Type=simple
      Restart=always
      ExecStart=/opt/mongodb_exporter/mongodb_exporter --mongodb.uri={{ mongodb_exporter_mongodb_uri }}

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
    create: true

- name: Enable the mongodb_exporter service
  ansible.builtin.systemd:
    name: mongodb_exporter.service
    state: started
    enabled: true
